# -*- coding: utf-8 -*-
"""Facial_Emotion_Detection_using_Yolo11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14owaj2qFi3kbjVgOUs7dqWJQI6WY1CKx

https://universe.roboflow.com/workenv-dayet/facial-emotion-dataset-7g1jd-hipbk
"""

!nvidia-smi

"""**Step 01 # Install the Ultralytics Package**"""

!pip install ultralytics

"""**Step 02 # Import All the Requried Libraries**"""

import ultralytics
ultralytics.checks()

from ultralytics import YOLO
from IPython.display import Image

"""**Step # 03 Download Dataset from Roboflow**"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="ZkNMlNnyIa2y7w8zGWMS")
project = rf.workspace("workenv-dayet").project("facial-emotion-dataset-7g1jd-hipbk")
version = project.version(3)
dataset = version.download("yolov11")

dataset.location

"""**Step # 04 Train YOLO11 Model on a Custom Dataset**"""

!yolo task=detect mode=train data={dataset.location}/data.yaml model="yolo11n.pt" epochs=100 imgsz=640

"""**Step # 05 Examine Training Results**"""

Image("/content/runs/detect/train/confusion_matrix.png", width=600)

Image("/content/runs/detect/train/labels.jpg", width=600)

Image("/content/runs/detect/train/results.png", width=600)

Image("/content/runs/detect/train/train_batch0.jpg", width=600)

Image("/content/runs/detect/train/val_batch0_pred.jpg", width=600)

"""**Step # 07  Validate Fine-Tuned Model**"""

!yolo task=detect mode=val model="/content/runs/detect/train/weights/best.pt" data={dataset.location}/data.yaml

"""**Step # 08 Inference with Custom Model on Images**"""

!yolo task=detect mode=predict model="/content/runs/detect/train/weights/best.pt" conf=0.25 source={dataset.location}/test/images save=True

import glob
import os
from IPython.display import Image as IPyImage, display

latest_folder = max(glob.glob('/content/runs/detect/predict*/'), key=os.path.getmtime)
for img in glob.glob(f'{latest_folder}/*.jpg')[1:4]:
    display(IPyImage(filename=img, width=600))
    print("\n")

